<?php
/**
 * Short description for file
 *
 * Long description for file (if any)...
 *
 * @category   Zend
 * @package    Zend_Mdg
 * @subpackage Giftregistry
 * @copyright  Copyright (c) 2018 ecommistry (http://www.ecommistry.com)
 * @license    http://framework.zend.com/license   BSD License
 * @version    Release: 1.0
 * @link       http://framework.zend.com/package/PackageName
 * @since      Class available since Release 1.0
 */

$registry = Mage::registry('loaded_registry'); ?>
<h3><?php echo $registry->getEventName(); ?></h3>
<p>
    <strong><?php $this->__('Event Date:') ?>
        <?php echo $registry->getEventDate(); ?>
    </strong>
</p>
<p>
    <strong><?php $this->__('Event Location:') ?>
        <?php echo $registry->getEventLocation(); ?>
    </strong>
</p>